### ISSUE TITLE
Feature Request: List seed in addition to displaying QR code

### ISSUE THREAD

**Issue by jfreedman0** [alexieong/2fas-backup-viewer-test#1]
Would be awesome if the HTML also simply lists the seed rather than only displaying the QR code.

**Comment by alexieong** [comment]
Seeds from different services are quite different in length. Displaying long seeds in pretty way is quite challenging (I've got some seeds with 52 characters long). Do you have any good idea?

**Comment by yyzguy** [comment]
I'm here to ask for the same thing.   I didn't realize the codes vary in length.   Perhaps break them into multiple lines if they exceed a certain number of characters.      I plan to use the output as an emergency sheet for another person who may not have device with a camera.

**Comment by alexieong** [comment]
Nice to see more request for this feature. Secret keys (seeds) will soon available in both on screen and printout. Stay tuned.

**Comment by alexieong** [comment]
Nice to see more request for this feature. Secret keys (seeds) is added in latest version. :)

**Comment by yyzguy** [comment]
Thank you so much!  I’m looking forward to checking it out later today.   Too difficult on iPhone:)
