### ISSUE TITLE
Distribution of modified GPLv3 licensed code

### ISSUE THREAD

**Issue by elliotwutingfeng** [alexieong/2fas-backup-viewer-test#3]
Hi,

I see that you are distributing code derived from [github.com/elliotwutingfeng/2fas-backup-decryptor](https://github.com/elliotwutingfeng/2fas-backup-decryptor), which was in turn derived from 2FAS Android [github.com/twofas/2fas-android](https://github.com/twofas/2fas-android); both repositories are under the GPLv3 license.

This repository's MIT license is incompatible with the above, it should be changed to GPLv3 or AGPLv3.

**Comment by alexieong** [comment]
Thanks for pointing out the license issue. The only thing I learned from the repository you mentioned is the encryption specification only. Is this still considered as “derived from”?

**Comment by elliotwutingfeng** [comment]
Yes, your decryption code is a port, and hence a derivative work based on the implementation written by 2FAS, which is specific to their vault format.

**Comment by alexieong** [comment]
Thanks for your explanation. License updated.

**Comment by alexieong** [comment]
According to the discussion here:
https://www.reddit.com/r/opensource/s/Y3v5PcCqa0

I'm just reading the encryption specifications and developing my own code. I'm wondering if it's necessary to change license type.

**Comment by elliotwutingfeng** [comment]
Hi, the UDMF format specifications in that reddit thread is distributed under the [GNU Free Documentation License](https://www.doomworld.com/eternity/engine/stuff/udmf10.txt). From what I know, this documentation license's copyleft only applies to the documentation, but not to software written to interpret the specifications.

In contrast, for 2FAS, the specifications for their vault format was not documented at all, it was inferred from their GPLv3 licensed source code. Particularly, [this file](https://github.com/twofas/2fas-android/blob/develop/core/cipher/src/main/java/com/twofasapp/cipher/backup/DataEncrypted.kt#L5) was used to determine how to interpet 2FAS's `servicesEncrypted` field.

**Comment by alexieong** [comment]
Understood. Thanks
