### ISSUE TITLE
Trouble with newest 39c9b13 release

### ISSUE THREAD

**Issue by yyzguy** [alexieong/2fas-backup-viewer-test#4]
The html code inside the downloaded zip file works great.   The output looks fantastic.    I had trouble with the html file located on the main page of the repository.   It didn't work and they appear to be different files.

When trying to print, I initially had trouble with pagination using Safari Browser.   I opened in Brave Browser and it paginated perfectly.    

Then I noticed the difference between the two.   Safari printing had "headers and footers" disabled.  Once headers and footers were enabled, the pagination was perfect.   Oddly, the two browsers seem to have different breakpoints for the pages, but that doesn't matter at all.  They are probably using different margins.

I see what you mean by the seeds have varying lengths.   All but one of mine take either one or two lines.   The long one takes up 12 lines!   I can see the QR code is much denser too.   Upon closer inspection it's using SHA256, while the others use SHA1

Thank you so much.    This is really helpful to have.    I also was able to discover I had a mistyped title on one of them and another was missing the username.  My guess is that was the fault of the original QR code.

**Comment by alexieong** [comment]
I've checked the HTML file directly from the main page of repo. There's no issue with me. How can we reproduce?

**Comment by yyzguy** [comment]
Perhaps I don't know the proper way to download files from Git.   I merely Right Click and download linked file.  It defaults to the same name as the contents of the zip file: 2fas-backup-viewer.html.    The one on the main page is 562KB.   The one from inside the zip is 26KB.     I'm nearly certain that's how I got the previous version without the seeds.

**Comment by alexieong** [comment]
I see. If you want to download the single file, you should click the "Download raw file" button on [this page](2fas-backup-viewer.html).
