### ISSUE TITLE
QR codes too close to each other

### ISSUE THREAD

**Issue by yyzguy** [alexieong/2fas-backup-viewer-test#5]
After printing the backup codes, I just got around to testing them.   I discovered that the QR codes are really close together and it's difficult for the camera (or maybe just me) to know which one is going to be used.    I think the best way to increase spacing would be to make the QR codes smaller rather than spreading them out further.    Would that be possible?

**Comment by alexieong** [comment]
I agree. Check out the latest commit?

**Comment by yyzguy** [comment]
> I agree. Check out the latest commit?

Yes!  Much better.   Thank you!
